### ISSUE TITLE
Frescobaldi cannot find Ghostscript

### ISSUE THREAD

**Issue by TimFierens** [frescobaldi/frescobaldi#1356]
I've recently installed LilyPond 2.21.80 on Mac OS 11.2 (Big Sur). It works just fine from the command line. But when I try to invoke LilyPond from inside Frescobaldi 3.1.3 (which I've also installed recently), I get the following error message:

`Converting to 'page2.pdf'...
warning: g_spawn_sync failed (0): gs: Failed to execute child process “gs” (No such file or directory)
fatal error: cannot rename 'page2-tmp-246279.417121.pdf' to 'page2.pdf'
Closed with return code 1.`

I'd be most grateful if someone could tell me what's the probable issue here, and how to remedy it.

**Comment by fedelibre** [comment]
How did you install LilyPond? Any reason to use 2.21.80 instead of 2.22.0? I would try the latter.

I know nothing about Mac but it seems #1305 is related.

**Comment by TimFierens** [comment]
> How did you install LilyPond? Any reason to use 2.21.80 instead of 2.22.0? I would try the latter.
> 
> I know nothing about Mac but it seems #1305 is related.

Thanks. I couldn't get MacPorts to work under OS 11.2 (it wouldn't recognize the Xcode command line tools), so I had to use the most recent version with an installer binary. I will definitely look into the other issue.

**Comment by asmod3us** [comment]
i use lilypond installed from homebrew and the check at

[/frescobaldi_app/job/lilypond.py#L176](https://github.com/frescobaldi/frescobaldi/blob/master/frescobaldi_app/job/lilypond.py#L176) fails for it, but it requires the same fix. (adding proper path so that Ghostscript is found). I replaced the line with

```
            if macosx.inside_app_bundle():
```

and that fixes it. For a proper PR I guess we'd want to detect installs via Homebrew in a similar fashion?

**Comment by rpspringuel** [comment]
I have LilyPond 2.22.1 installed via MacPorts and get the same issue.

**Comment by jsfelix** [comment]
Same problema here with macOS Big Sur 11.6.

Installed Lilypond with homebrew:
```
brew install lilypond
```

Installed Frescobaldi with homebrew:
```
brew install --cask frescobaldi
```

I noticed that frescobaldi try to rename a pdf file that has different name:
```
fatal error: cannot rename `test-tmp-8548562.221901.pdf' to `test.pdf'
```

Searching on Finder, this file is named `test-tmp-8548562` (without .pdf extension).

**Comment by stweil** [comment]
Frescobaldi on MacOS with Homebrew is fixed by pull request #1397.

**Comment by brumleygap** [comment]
I am not sure how long the changes take to find their way into brew, but I just installed lilypond and frescobaldi using brew as above and I still getting the gs error and "cannot rename" errors 

```
Converting to `test.pdf'...
warning: g_spawn_sync failed (0): gs: Failed to execute child process “gs” (No such file or directory)
fatal error: cannot rename `test-tmp-418443.679892.pdf' to `test.pdf'

```

**Comment by jsfelix** [comment]
Changes happen in Homebrew only when a new version is released upstream. So, as #1397 is still open, you need to patch the commits there to solve the problem.

**Comment by cyndi5** [comment]
@jsfelix Thank you!!! The patch fixed the exact same issue I had using the homebrew frescobaldi app.

**Comment by dliessi** [comment]
#1397 has been merged to `master`.

**Comment by SooLee** [comment]
I am using Frescobaldi installed through `brew --cask` (just reinstalled) and did the patch as below:
```bash
cd /Applications/Frescobaldi.app/Contents/Resources/lib/python3.9
curl https://patch-diff.githubusercontent.com/raw/frescobaldi/frescobaldi/pull/1397.patch | patch -s -p1
```
I get the same error message when I use Eclipse Elysium.
```
warning: g_spawn_sync failed (0): gs: Failed to execute child process “gs” (No such file or directory)
fatal error: cannot rename `test-lily-tmp-155634.393801.pdf' to `test-lily.pdf'
```
Any clue?

**Comment by brumleygap** [comment]
I got the same error messages on my Mac Air after a fresh install using
brew. I did not patch and I started Frescobaldi using Frescobaldi.app.

**Comment by wurzelsand** [comment]
Frescobaldi still cannot call ghostscript. Apparently MacOS forbids the command chain frescobaldi->lilypond->ghostscript.

**Workaround**:

* Open *Security & Privacy* (System Preferences).
* Select the *Privacy* tab.
* Search in the left table for *Developer Tools*.
* Add *Frescobaldi.app* here.

**Comment by wurzelsand** [comment]
No, it is exactly the same error message with `gs: Failed to execute child process "gs" (No such file or directory)`. By the way, I don't have to explicitly specify the path to *lilypond* (as described in the link), *Frescobaldi* finds it like that.

One thing is strange: I can remove *Frescobaldi.app* from the list of *Developer Tools* without changing anything. So it is not possible for me to reproduce the error message at the moment.

**Comment by wurzelsand** [comment]
I have to take it all back: It was my mistake. I had initially run the patch for version 3.1.3, but when it didn't work right away, it worked after I changed the security settings. Just as well I probably could have done a system reboot.

I have now installed Frescobaldi 3.2 via MacPorts and everything works beautifully. The new version is not yet offered via Homebrew. 

However, it would be nice if a *.dmg file for 3.2 and not only for 3.1.3 was offered on https://github.com/frescobaldi/frescobaldi/releases. Via MacPorts it takes a few hours until everything is compiled.
